import { CSSProperties, FC } from 'react';
import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  AlertCircle,
  AlertTriangle,
  Bell,
  Bold,
  Calendar,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Clock,
  CloudUpload,
  Code,
  Trophy,
  Download,
  Eraser,
  Eye,
  EyeOff,
  FileDown,
  FileUp,
  Heading1,
  Heading2,
  Image,
  Info,
  Inbox,
  Italic,
  Key,
  LayoutGrid,
  Link,
  List,
  ListOrdered,
  Loader2,
  LucideProps,
  Mail,
  Minus,
  Banknote,
  PanelLeftClose,
  PanelRightClose,
  Pencil,
  Phone,
  Pilcrow,
  Plus,
  Printer,
  Quote,
  Redo,
  Search,
  SlidersVertical,
  SquarePen,
  Store,
  Strikethrough,
  Trash2,
  Underline,
  Undo,
  Unlink,
  Upload,
  User,
  Users,
  Video,
  Wallet,
  Home,
  X,
  XCircle,
} from 'lucide-react';

export type IconProps = {
  className?: string;
  style?: CSSProperties;
  strokeWidth?: number;
};

export type Icon = FC<IconProps>;

const iconMap = {
  'home':                       Home,
  'home-solid':                 Home,
  'arrow-up-tray':              Upload,
  'arrow-up-tray-solid':        Upload,
  'loading':                    Loader2,
  'magnifying-glass':           Search,
  'envelope':                   Mail,
  'key':                        Key,
  'phone':                      Phone,
  'check-circle':               CheckCircle,
  'eye':                        Eye,
  'eye-slash':                  EyeOff,
  'check':                      Check,
  'check-v2':                   Check,
  'minus':                      Minus,
  'trash':                      Trash2,
  'trash-solid':                Trash2,
  'exclamation-triangle':       AlertTriangle,
  'exclamation-circle':         AlertCircle,
  'x-mark':                     X,
  'x-circle':                   XCircle,
  'vuesax-arrow-down':          ChevronDown,
  'vuesax-arrow-up':            ChevronUp,
  'vuesax-arrow-left':          ChevronLeft,
  'vuesax-arrow-right':         ChevronRight,
  'caret-down-fill':            ChevronDown,
  'caret-up-fill':              ChevronUp,
  'inbox':                      Inbox,
  'chevron-double-left':        ChevronsLeft,
  'chevron-double-right':       ChevronsRight,
  'cloud-arrow-up':             CloudUpload,
  'user':                       User,
  'chevron-down':               ChevronDown,
  'calendar':                   Calendar,
  'calendar-solid':             Calendar,
  'calendar-days':              CalendarDays,
  'calendar-days-solid':        CalendarDays,
  'calendar-date-range':        CalendarRange,
  'calendar-date-range-solid':  CalendarRange,
  'clock':                      Clock,
  'clock-solid':                Clock,
  'undo':                       Undo,
  'redo':                       Redo,
  'bold':                       Bold,
  'italic':                     Italic,
  'underline':                  Underline,
  'strikethrough':              Strikethrough,
  'code':                       Code,
  'link':                       Link,
  'link-off':                   Unlink,
  'h1':                         Heading1,
  'h2':                         Heading2,
  'paragraph':                  Pilcrow,
  'list':                       List,
  'list-ordered':               ListOrdered,
  'ul':                         List,
  'ol':                         ListOrdered,
  'left':                       AlignLeft,
  'center':                     AlignCenter,
  'right':                      AlignRight,
  'justify':                    AlignJustify,
  'eraser':                     Eraser,
  'image':                      Image,
  'video':                      Video,
  'quote':                      Quote,
  'pencil':                     Pencil,
  'pencil-square':              SquarePen,
  'vuesax-element':             LayoutGrid,
  'user-group':                 Users,
  'users':                      Users,
  'building-storefront':        Store,
  'vuesax-empty-wallet-change': Wallet,
  'vuesax-money-receive':       Banknote,
  'collapse-left':              PanelLeftClose,
  'collapse-right':             PanelRightClose,
  'bell':                       Bell,
  'adjustments-vertical':       SlidersVertical,
  'plus':                       Plus,
  'information-circle':         Info,
  'arrow-down-tray':            Download,
  'printer':                    Printer,
  'vuesax-document-upload':     FileUp,
  'vuesax-document-download':   FileDown,
  'trophy':                     Trophy,
} satisfies Record<string, FC<LucideProps>>;

export type IconName = keyof typeof iconMap;

export const RenderIcon = ({
  name,
  className,
  style,
  strokeWidth,
}: IconProps & { name?: IconName }) => {
  if (!name) return null;
  const Icon = iconMap[name];
  if (!Icon) return null;

  const isLoading = name === 'loading';

  return (
    <Icon
      className={className}
      style={style}
      strokeWidth={strokeWidth}
      {...(isLoading ? { 'data-loading': true } : {})}
    />
  );
};
